Repository input-output-hk/cardano-benchmarking, pull requests merged in 2020-06, with the labels that each got.

#74 CAD-743 RTS display; peers list
  cardano-rt-view/src/Cardano/Benchmarking/RTView/GUI/NodeWidget.hs
  cardano-rt-view/src/Cardano/Benchmarking/RTView/GUI/Updater.hs
  cardano-rt-view/src/Cardano/Benchmarking/RTView/NodeState/Updater.hs
Labels: maintenance

#78 more deps required by stack
  stack.yaml
Labels: maintenance

#77 adapt to upstream changes in tracers
  scripts/blocksizes.sh
  scripts/recvmsgblock.sh
Labels: maintenance

#79 CAD-890 RTview on Windows
  cardano-rt-view/src/Cardano/Benchmarking/RTView/CLI.hs
  cardano-rt-view/src/Cardano/Benchmarking/RTView/NodeState/Updater.hs
Labels: maintenance

#87 CAD-1233 updated build environment and dependencies
  benchmarks/chain-sync/benchmark-chain-sync-mainnet.sh
  benchmarks/chain-sync/configuration/log-configuration.yaml
  cabal.project
  nix/stack-shell.nix
  stack.yaml
Labels: maintenance

#90 CAD-1201 restore shelley3pools benchmark
  benchmarks/shelley3pools/configuration/configuration-node-1.yaml
  benchmarks/shelley3pools/configuration/configuration-node-2.yaml
  benchmarks/shelley3pools/configuration/configuration-node-3.yaml
Labels: maintenance

#93 new dep: bech32
  stack.yaml
Labels: maintenance

#98 update script
  benchmarks/shelley3pools/fund-addresses.sh
Labels: maintenance

#99 CAD-1193 show combined sys+user CPU %
  cabal.project
  cardano-rt-view/src/Cardano/Benchmarking/RTView/NodeState/Updater.hs
  scripts/grep-cpu.sh
  stack.yaml
Labels: enhancement, maintenance

#101 time to block: scripts to extract tx
  benchmarks/shelley3pools/analyse.sh
  scripts/adoptedblock.sh
  scripts/extract_adopted_tx_ids.sh
  scripts/libconfig.sh
  scripts/mempooladdedtx.sh
  scripts/mempoolrejectedtx.sh
  scripts/switchedtoafork.sh
  scripts/tryswitchtoafork.sh
Labels: enhancement

#112 CAD-1267 comment out references to packages in submodules
  stack.yaml
Labels: bug

#53 CAD-992, CAD-974, CAD-1130, CAD-1241, CAD-1231: txgen: shelley support + single shared pool + cleaner submission + updates
  .buildkite/pipeline.yml
  cabal.project
  cardano-tx-generator/app/cardano-tx-generator.hs
  cardano-tx-generator/cardano-tx-generator.cabal
  cardano-tx-generator/src/Cardano/Benchmarking/GeneratorTx.hs
  cardano-tx-generator/src/Cardano/Benchmarking/GeneratorTx/CLI/Parsers.hs
  cardano-tx-generator/src/Cardano/Benchmarking/GeneratorTx/CLI/Run.hs
  cardano-tx-generator/src/Cardano/Benchmarking/GeneratorTx/Error.hs
  cardano-tx-generator/src/Cardano/Benchmarking/GeneratorTx/NodeToNode.hs
  cardano-tx-generator/src/Cardano/Benchmarking/GeneratorTx/Submission.hs
  cardano-tx-generator/src/Cardano/Benchmarking/GeneratorTx/Tx.hs
  cardano-tx-generator/src/Cardano/Benchmarking/Util.hs
  default.nix
  nix/default.nix
  nix/haskell.nix
  nix/nixos/tx-generator-service.nix
  nix/sources.json
  release.nix
  stack.yaml
Labels: enhancement, maintenance

#114 CAD-1230: integrate txgen with shelley3pools
  benchmarks/shelley3pools/benchmark.sh
  benchmarks/shelley3pools/configuration/configuration-generator.yaml
  benchmarks/shelley3pools/configuration/configuration-node-1.yaml
  benchmarks/shelley3pools/configuration/configuration-node-2.yaml
  benchmarks/shelley3pools/configuration/configuration-node-3.yaml
  benchmarks/shelley3pools/configuration/parameters
  benchmarks/shelley3pools/create-addresses.sh
  benchmarks/shelley3pools/prepare_genesis.sh
  benchmarks/shelley3pools/run-3pools.sh
  benchmarks/shelley3pools/run-tx-generator.sh
  benchmarks/shelley3pools/submit_delegation_tx.sh
Labels: maintenance
