Repository input-output-hk/cardano-benchmarking, pull requests merged in 2020-05, with the labels that each got.

#43 CAD-918: switch to cabal.project-based pinning for the node and db-sync
  cabal.project
  nix/sources.json
Labels: enhancement

#44 sync repo pinning for Release 1.11 to stack.yaml
  stack.yaml
Labels: maintenance

#46 CAD-878: Node's up time.
  cardano-rt-view/src/Cardano/Benchmarking/RTView/NodeState/Types.hs
  cardano-rt-view/src/Cardano/Benchmarking/RTView/NodeState/Updater.hs
Labels: maintenance

#50 CAD-878 uptime in 'metrics' context name
  cardano-rt-view/src/Cardano/Benchmarking/RTView/NodeState/Updater.hs
Labels: maintenance

#56 adapted nightly full sync bm
  benchmarks/chain-sync/ci-full-sync.sh
Labels: maintenance

#60 grep metrics from Prometheus port as in local configuration
  benchmarks/chain-sync/ci-full-sync.sh
Labels: maintenance

#64 CAD-977 recreate timeline of block creation and diffusion
  .gitignore
  benchmarks/cluster3nodes/README
  benchmarks/cluster3nodes/README.md
  bm-timeline/LICENSE
  bm-timeline/NOTICE
  bm-timeline/README.md
  bm-timeline/Setup.hs
  bm-timeline/bm-timeline.cabal
  bm-timeline/src/Cardano/BM/AddToChain.hs
  bm-timeline/src/Cardano/BM/Adopted.hs
  bm-timeline/src/Cardano/BM/Common.hs
  bm-timeline/src/Cardano/BM/Leader.hs
  bm-timeline/src/Timeline.hs
  cabal.project
  scripts/addedblocktoqueue.sh
  scripts/addedtocurrentchain.sh
  scripts/adoptedblock.sh
  scripts/nodeisleader.sh
  scripts/recvmsgblock.sh
  stack.yaml
Labels: enhancement

#69 document 'reconstruct-timeline'
  benchmarks/cluster3nodes/README.md
  bm-timeline/README.md
Labels: documentation

#72 CAD-1075 rename existing tx-gen for Byron
  benchmarks/cluster3nodes/run_tx_generator.sh
  benchmarks/cluster3nodes/start.sh
  cardano-tx-generator/app/cardano-tx-generator-byron.hs
  cardano-tx-generator/cardano-tx-generator.cabal
  default.nix
  nix/nixos/tx-generator-service.nix
  release.nix
  scripts/libconfig.sh
Labels: maintenance
